"""Add Alumno, Curso, Asistencia, RegistroAcademico models

Revision ID: 7d67ac6c1bcc
Revises: 4f8bfdd4a179
Create Date: 2025-11-05 18:58:21.795785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d67ac6c1bcc'
down_revision = '4f8bfdd4a179'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cursos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=False),
    sa.Column('nivel', sa.String(length=20), nullable=False),
    sa.Column('division', sa.String(length=10), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('alumnos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=80), nullable=False),
    sa.Column('apellido', sa.String(length=80), nullable=False),
    sa.Column('dni', sa.String(length=20), nullable=True),
    sa.Column('curso_id', sa.Integer(), nullable=False),
    sa.Column('promedio_g2', sa.Float(), nullable=True),
    sa.Column('materias_previas', sa.Integer(), nullable=False),
    sa.Column('inasistencias', sa.Integer(), nullable=False),
    sa.Column('tiempo_estudio_semanal', sa.String(length=50), nullable=True),
    sa.Column('nivel_riesgo', sa.String(length=20), nullable=True),
    sa.Column('precision_prediccion', sa.Float(), nullable=True),
    sa.Column('factores_riesgo', sa.Text(), nullable=True),
    sa.Column('recomendacion', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('fecha_actualizacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['curso_id'], ['cursos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dni')
    )
    op.create_table('asistencias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alumno_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('presente', sa.Boolean(), nullable=False),
    sa.Column('justificada', sa.Boolean(), nullable=False),
    sa.Column('observaciones', sa.Text(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['alumno_id'], ['alumnos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('registros_academicos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alumno_id', sa.Integer(), nullable=False),
    sa.Column('periodo', sa.String(length=50), nullable=False),
    sa.Column('promedio', sa.Float(), nullable=True),
    sa.Column('materias_aprobadas', sa.Integer(), nullable=False),
    sa.Column('materias_desaprobadas', sa.Integer(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['alumno_id'], ['alumnos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_creacion', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_column('fecha_creacion')

    op.drop_table('registros_academicos')
    op.drop_table('asistencias')
    op.drop_table('alumnos')
    op.drop_table('cursos')
    # ### end Alembic commands ###
